### ISSUE TITLE
Background applications also registering gamepad input while panel is open

### ISSUE THREAD

**Issue by pdien** [project-sbc/Handheld-Hardware-Tools#9] opened 2024-06-07 20:55 UTC
When opening the panel and navigating around, gamepad controls are still working for the background application which causes input to be registered in games when trying to select options in the panel.

I can't imagine there being a way for Windows to block input to unfocused applications.

**Comment by project-sbc** [comment] 2024-06-11 02:26
I have this somewhat implemented, but ill have to check the specifics. What game did you use this on?

**Comment by pdien** [comment] 2024-06-13 02:00
It wasn't any specific game, but any game or application that also uses gamepad input.
For example, when using the menu while playing a game (Ghost of Tsushima) inputs are still registering in the game as I am navigating the HHT menu.

**Comment by project-sbc** [comment] 2024-06-13 15:30
Yeah it’s not working as intended, I’m working on it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by project-sbc** [comment] 2024-07-11 22:51
I think i fixed this in the mousedev branch, it will be merged soon when i finish mouse mode button modifications

**Closed** 2024-07-16 16:54 UTC
